comment_width = 90
force_multiline_blocks = true
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 120
imports_granularity = "Crate"
reorder_impl_items = true
use_small_heuristics = "Off"
wrap_comments = true
